name: CopyCat
on:
  push:
    paths:
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy file
        uses: canastro/copy-action@0.0.2
        with:
          source: CHANGELOG.md
          target: README.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m ":rocket: Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
